id = "finitescript"
name = "FiniteScript"
version = "0.0.1"
schema_version = 1
authors = ["Finite Systems"]
description = "FiniteScript language support for Zed."
repository = "https://github.com/finitesystemscorp/zed-finitescript"

[grammars.finitescript]
repository = "https://github.com/finitesystemscorp/zed-finitescript"
rev = "main"
